# Generated by Django 5.0.7 on 2024-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                ("plot", models.TextField()),
                ("type", models.CharField(max_length=20)),
                ("poster", models.ImageField(upload_to="")),
                ("box_office", models.IntegerField()),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
